[theme]
primaryColor="#ffffff" # Blue color (for primary elements, buttons, etc.)
backgroundColor="#0077b6" # White color (for the main background)
secondaryBackgroundColor="#f0f0f0" # Light gray color (for secondary backgrounds, containers, etc.)
textColor="#333333" # Dark gray color (for text)
font="sans serif"